import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  workspaceClaudeFilesSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
